name: quanlydoisong
description: "A new Flutter project."
publish_to: 'none' 
<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.4
  get: ^4.6.5
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  intl: ^0.19.0
  path_provider: ^2.0.0
  table_calendar: ^3.0.7
  uuid: ^4.5.0
  google_sign_in: ^6.2.2 
  google_generative_ai: ^0.4.6
  flutter_local_notifications: ^18.0.1
  flutter_lints: ^4.0.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.0.0
  firebase_messaging: ^15.1.6
  flutter_spinkit: ^5.1.0
  lottie: ^3.1.3
  collection: ^1.17.1
  excel: ^2.1.0
  flutter_typeahead: ^3.1.3
  # web3dart: ^2.7.3
  # http: ^0.13.5
  # ipfs_client: ^0.2.0
  syncfusion_flutter_gauges: ^20.4.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

<<<<<<< Updated upstream
  
  assets:
    - assets/logo.png
    - assets/vietnam_provinces.json
=======
  assets:
    - assets/logo.png
    - assets/vietnam_provinces.json
    - assets/header_background.png
>>>>>>> Stashed changes
